#ifndef LIBIOCTOMAP_GLOBAL_H
#define LIBIOCTOMAP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBIOCTOMAP_LIBRARY)
#  define LIBIOCTOMAPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBIOCTOMAPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBIOCTOMAP_GLOBAL_H
